FROM quay.io/keycloak/keycloak:26.0.7

# Set environment variables to configure Keycloak
ENV QUARKUS_DATASOURCE_USER_STORE_DB_KIND=${QUARKUS_DATASOURCE_USER_STORE_DB_KIND:-postgresql} \
    QUARKUS_DATASOURCE_USER_STORE_USERNAME=${QUARKUS_DATASOURCE_USER_STORE_USERNAME:-postgres} \
    QUARKUS_DATASOURCE_USER_STORE_PASSWORD=${QUARKUS_DATASOURCE_USER_STORE_PASSWORD:-secret} \
    QUARKUS_DATASOURCE_USER_STORE_JDBC_URL=${QUARKUS_DATASOURCE_USER_STORE_JDBC_URL:-jdbc:postgresql://postgres:5432/karas} \
    QUARKUS_DATASOURCE_USER_STORE_JDBC_TRANSACTIONS=${QUARKUS_DATASOURCE_USER_STORE_JDBC_TRANSACTIONS:-xa} \
    QUARKUS_HIBERNATE_ORM_LOG_SQL=${QUARKUS_HIBERNATE_ORM_LOG_SQL:-true}

# Copy the JAR files from the local ./keycloak/providers directory to /opt/keycloak/providers/
COPY --chown=keycloak keycloak/providers/*.jar /opt/keycloak/providers/
COPY --chown=keycloak keycloak/conf/* /opt/keycloak/conf/
COPY --chown=keycloak keycloak/import/* /opt/keycloak/data/import/

RUN ls -la .

# Make the JAR and config files available to Keycloak
RUN /opt/keycloak/bin/kc.sh build \
    --spi-provider=/opt/keycloak/providers \
    --spi-config-dir=/opt/keycloak/conf

RUN /opt/keycloak/bin/kc.sh show-config

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm", "--import-file=/opt/keycloak/data/import/karas-keycloak-realm.json"]