services:
  postgres:
    image: 'postgres:latest'
    restart: always
    env_file: '.env.developmental'
    ports:
      - '5431:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nginx_network
  backend:
    container_name: karas-backend-spring-boot
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: '.env.developmental'
    image: karas-backend-spring-boot:latest
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005
    networks:
      - nginx_network
networks:
  nginx_network:
    external: true
volumes:
  postgres-data: