services:
  postgres:
    image: 'postgres:latest'
    restart: always
    env_file: '.env'
    ports:
      - '5431:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    container_name: karas-backend-spring-boot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: '.env'
    image: karas-backend-spring-boot:latest
    depends_on:
      - postgres
    working_dir: /app
    ports:
      - 8080:8080
