services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: karas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - '5431:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    container_name: karas-backend-spring-boot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/karas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    image: karas-backend-spring-boot:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres
