services:
  postgres:
    image: 'postgres:latest'
    restart: always
    env_file: '.env'
    environment:
      PGDATA: /var/lib/pg_data
    ports:
      - '5431:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data:z
    networks:
      - nginx_network
  backend:
    image: "ghcr.io/chheangg/karas-backend:latest"
    container_name: karas-backend-spring-boot
    build:
      context: .
      dockerfile: Dockerfile
    user: 1000:1000
    env_file: '.env'
    depends_on:
      - postgres
    working_dir: /app
    ports:
      - 8080:8080
    networks:
      - nginx_network
  keycloak:
    container_name: karas-keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    command:
      - start-dev
      - --import-realm
    ports:
      - 3000:3000
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    env_file: '.env'
    environment:
      KC_HTTP_PORT: 3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx_network
networks:
  nginx_network:
    external: true
volumes:
  postgres-data: