services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: karas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - '5431:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data