ALTER TABLE vehicle
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE vehicle
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE customer
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE customer
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE category
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE category
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE subcategory
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE subcategory
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE product
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE product
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE unit
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE unit
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE restock
    ALTER COLUMN created_at SET DEFAULT NOW();

ALTER TABLE restock
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE restock_item
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE restock_item
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE sale
    ALTER COLUMN created_at SET DEFAULT NOW();

ALTER TABLE sale
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE item
    ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

ALTER TABLE item
    ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW();

