name: Build and Deploy Backend to Digital Ocean
run-name: ${{ github.actor }} is deploying to production server 🚀
on:
  push:
    branches:
      - main
jobs:
  DeployToMain:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend application on production server
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{secrets.SSH_HOST}}
            username: ${{secrets.SSH_USERNAME}}
            password: ${{secrets.SSH_PASSWORD}}
            script: |              
              echo "Clone repo"
              git clone git@github.com:Indraneers/karas-backend.git
              cd ./karas-backend
              
              echo "Make ENV file"
              touch .env
              echo "${{secrets.PROD_ENV_FILE}}" > .env
              
              echo "Deploy image"
              docker compose down
              docker compose build --no-cache
              docker compose up -d
          
