name: Build and deploy backend to Digital Ocean
run-name: ${{ github.actor }} is deploying to main server 🚀
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    name: build and publish image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login into ghcr.io
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create .env.keycloak file
        run: |
          echo "${{ secrets.KEYCLOAK_ENV_FILE }}" > .env.keycloak
          echo "Contents of .env.keycloak:"
          cat .env.keycloak
          echo "Listing files in the directory:"
          ls -la

      - name: Build and Publish
        run: |
          docker compose -f docker-compose.yml build --no-cache
          docker compose -f docker-compose.yml push
  deployment:
    needs: build-and-publish
    name: deploy image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [v1, v2]
    steps:
      - uses: actions/checkout@v3

      - name: rsync docker compose config
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: docker-compose.yml
          remote_path: karas-backend
          remote_host: ${{ secrets[format('SSH_PROD_{0}_HOST', matrix.env)] }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: connect and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets[format('SSH_PROD_{0}_HOST', matrix.env)] }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker system prune -a --volumes
            docker network create nginx_network
            cd karas-backend

            touch .env
            touch .env.keycloak
            echo "${{ secrets[format('PROD_{0}_ENV_FILE', matrix.env)] }}" > .env
            echo ${{ secrets.KEYCLOAK_ENV_FILE }} > .env.keycloak

            echo "${{ secrets.PAT }}" | docker login ghcr.io --username "${{ github.actor }}" --password-stdin
            docker compose pull
            docker compose --env-file .env up -d
            
            cd ../karas-frontend
            docker compose restart